/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: my-fileBrowser.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _MY_FILEBROWSER_H_
#define _MY_FILEBROWSER_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef my_fileBrowser__ns
#define my_fileBrowser__ns 1656029283
#define my_fileBrowser__ns_id "urn:my:my-fileBrowser"
#define my_fileBrowser__ns_uri "urn:my:my-fileBrowser"
#endif

#define my_fileBrowser_filename 410894381
#define my_fileBrowser_files 1813401332
#define my_fileBrowser_session 1896174846
#define my_fileBrowser_success 1
#define my_fileBrowser_failure 0
#define my_fileBrowser_file 867066344
#define my_fileBrowser_sessions 972148830
#define my_fileBrowser_file_browser 533923630
#define my_fileBrowser_size 1649058097
#define my_fileBrowser_creation_timestamp 1289028435
#define my_fileBrowser_vnfs 941257423
#define my_fileBrowser_session_id 372565948
#define my_fileBrowser_vnf_id 1996685037
#define my_fileBrowser_vnf 564955152
#define my_fileBrowser__callpointid_fileBrowserCP "fileBrowserCP"

#ifdef __cplusplus
}
#endif

#endif
